# Generated by Django 5.2.8 on 2025-12-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Учебное заведение')),
                ('faculty', models.CharField(max_length=200, verbose_name='Факультет/Специальность')),
                ('start_year', models.IntegerField(verbose_name='Год начала')),
                ('end_year', models.IntegerField(verbose_name='Год окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['-end_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('current', models.BooleanField(default=False, verbose_name='Текущее место работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('technologies', models.CharField(blank=True, max_length=300, verbose_name='Технологии')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('title', models.CharField(max_length=200, verbose_name='Должность/Специализация')),
                ('about', models.TextField(verbose_name='О себе')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Местоположение')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Персональная информация',
                'verbose_name_plural': 'Персональная информация',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название технологии')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-имя')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Базы данных'), ('devops', 'DevOps'), ('mobile', 'Мобильная разработка'), ('cloud', 'Облачные технологии'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
                ('level', models.IntegerField(choices=[(1, 'Начальный'), (2, 'Базовый'), (3, 'Средний'), (4, 'Продвинутый'), (5, 'Эксперт')], default=3, verbose_name='Уровень владения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('icon_class', models.CharField(blank=True, help_text='Например: bi-github, bi-python, bi-react', max_length=50, null=True, verbose_name='Класс иконки (Bootstrap Icons)')),
                ('icon_color', models.CharField(blank=True, default='#3a6656', help_text='HEX код цвета, например: #3a6656', max_length=20, null=True, verbose_name='Цвет иконки')),
                ('bg_color', models.CharField(blank=True, default='#e9f0e8', help_text='HEX код цвета фона', max_length=20, null=True, verbose_name='Цвет фона')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('experience_years', models.FloatField(default=0, verbose_name='Лет опыта')),
                ('last_used', models.DateField(blank=True, null=True, verbose_name='Последнее использование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['order', 'category', 'name'],
                'indexes': [models.Index(fields=['slug'], name='core_techno_slug_ce219a_idx'), models.Index(fields=['category'], name='core_techno_categor_f5b509_idx'), models.Index(fields=['is_active'], name='core_techno_is_acti_68c293_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps'), ('database', 'Database'), ('other', 'Other')], default='backend', max_length=20, verbose_name='Категория')),
                ('proficiency', models.IntegerField(default=50, help_text='От 0 до 100', verbose_name='Уровень владения (%)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='core.technology', verbose_name='Связанная технология')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('project_type', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('desktop', 'Desktop Application'), ('other', 'Other'), ('api', 'API Development')], default='web', max_length=20, verbose_name='Тип проекта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub ссылка')),
                ('live_url', models.URLField(blank=True, verbose_name='Демо ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_featured', models.BooleanField(default=False, verbose_name='В избранном')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('year', models.IntegerField(blank=True, help_text='Например: 2024', null=True, verbose_name='Год реализации')),
                ('technologies', models.ManyToManyField(blank=True, help_text='Технологии, использованные в проекте', related_name='projects', to='core.technology', verbose_name='Технологии')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
